app:
  name: "Spotify Final Project"
  author: "..."
  debug: false

data:
  dataset_path: "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv"
  id_column: "track_id"
  title_column: "track_name"
  artist_column: "artist_name"

features:
  primary_feature: "danceability"
  secondary_filters:
    - "energy"
    - "valence"
  allowed_features:
    - danceability
    - energy
    - valence
    - acousticness
    - instrumentalness
    - liveness
    - loudness
    - speechiness
    - tempo
    - duration_ms
    - key
    - mode

logging:
  level: "INFO"
  log_to_file: true
  file_path: "logs/app.log"

performance:
  cache_results: true
  cache_ttl_seconds: 600 #cache similarity computations for 10 minutes
